### ISSUE TITLE
Problems running waf build

### ISSUE THREAD

**Issue by JuanCabre** [steinwurf/kodo-rlnc-go#1]
Hello guys, 
I am trying to build the project, but I am having problems with it. I am using python 3.7.3. Python waf configure runs correctly, all green, but when I try to run python waf configure, I get the following error: 

```
Load "waf-tools"                         : resolve_symlinks/waf-tools => /home/juan/dev/kodo-rlnc-go/resolved_dependencies/waf-tools-ae40a5/4.27.0-47f262 
Load "kodo-rlnc-c"                       : resolve_symlinks/kodo-rlnc-c => /home/juan/dev/kodo-rlnc-go/resolved_dependencies/kodo-rlnc-c-d82d69/2.0.0-de813f 
Load "kodo-rlnc"                         : resolve_symlinks/kodo-rlnc => /home/juan/dev/kodo-rlnc-go/resolved_dependencies/kodo-rlnc-acd412/11.0.0-97d7aa 
Load "kodo-core"                         : resolve_symlinks/kodo-core => /home/juan/dev/kodo-rlnc-go/resolved_dependencies/kodo-core-f711a6/18.1.0-256ed9 
Load "boost"                             : resolve_symlinks/boost => /home/juan/dev/kodo-rlnc-go/resolved_dependencies/boost-6990ca/3.1.8-4a14f1 
Load "allocate"                          : resolve_symlinks/allocate => /home/juan/dev/kodo-rlnc-go/resolved_dependencies/allocate-ddb961/3.0.0-b524c0 
Load "fifi"                              : resolve_symlinks/fifi => /home/juan/dev/kodo-rlnc-go/resolved_dependencies/fifi-f85dcd/29.3.0-3be54e 
Load "cpuid"                             : resolve_symlinks/cpuid => /home/juan/dev/kodo-rlnc-go/resolved_dependencies/cpuid-a4173a/5.0.2-da9c40 
Load "platform"                          : resolve_symlinks/platform => /home/juan/dev/kodo-rlnc-go/resolved_dependencies/platform-e774c1/3.1.0-8f9502 
Load "storage"                           : resolve_symlinks/storage => /home/juan/dev/kodo-rlnc-go/resolved_dependencies/storage-a97dfa/4.0.1-d7a702 
Load "hex"                               : resolve_symlinks/hex => /home/juan/dev/kodo-rlnc-go/resolved_dependencies/hex-4a4db2/4.1.1-f51a77 
Load "endian"                            : resolve_symlinks/endian => /home/juan/dev/kodo-rlnc-go/resolved_dependencies/endian-10cf49/9.0.0-e8e540 
Traceback (most recent call last):
  File "/home/juan/dev/kodo-rlnc-go/.waf3-1.9.8-f041daa8217a21e7300a58146384a779/waflib/Node.py", line 295, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/juan/dev/kodo-rlnc-go/.waf3-1.9.8-f041daa8217a21e7300a58146384a779/waflib/Scripting.py", line 120, in waf_entry_point
    run_commands()
  File "/home/juan/dev/kodo-rlnc-go/.waf3-1.9.8-f041daa8217a21e7300a58146384a779/waflib/Scripting.py", line 181, in run_commands
    ctx=run_command(cmd_name)
  File "/home/juan/dev/kodo-rlnc-go/.waf3-1.9.8-f041daa8217a21e7300a58146384a779/waflib/Scripting.py", line 172, in run_command
    ctx.execute()
  File "/home/juan/dev/kodo-rlnc-go/.waf3-1.9.8-f041daa8217a21e7300a58146384a779/waflib/Scripting.py", line 362, in execute
    return execute_method(self)
  File "/home/juan/dev/kodo-rlnc-go/.waf3-1.9.8-f041daa8217a21e7300a58146384a779/waflib/Build.py", line 98, in execute
    self.load_envs()
  File "/home/juan/dev/kodo-rlnc-go/.waf3-1.9.8-f041daa8217a21e7300a58146384a779/waflib/Build.py", line 78, in load_envs
    lst=node.ant_glob('**/*%s'%CACHE_SUFFIX,quiet=True)
  File "/home/juan/dev/kodo-rlnc-go/.waf3-1.9.8-f041daa8217a21e7300a58146384a779/waflib/Node.py", line 344, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/home/juan/dev/kodo-rlnc-go/.waf3-1.9.8-f041daa8217a21e7300a58146384a779/waflib/Node.py", line 344, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
```

I could not understand what the problem is since I am not familiar with the waf build system.

Update: It seems to be a problem with the python version. When I use python 2.7.16 it works just fine.

Cheers,
JC

**Comment by jpihl** [comment]
Hi Juan,

It seems waf that version of waf didn't support that version of python.
I've update waf, can you try again and see if this solves your issue?

**Comment by JuanCabre** [comment]
Now it works like a charm!
Thanks Jeppe.
