### ISSUE TITLE
Extending the API - Changing kodo-c to Major 4

### ISSUE THREAD

**Issue by JuanCabre** [steinwurf/kodo-rlnc-go#3]
Hello guys,
I am trying to extend the API because I need the functionalities of write and read symbols, as well as the ability to recode (write_payload at the decoder). I would like to add them and make a pull request. However, I am having issues. The Go bindings resolve to kodo-rlnc-c major 2, and in that major version does not include these APIs. I tried to change the resolve to major 4 to update the go bindings. Everything goes well with configure and build, but when I run this command
`python waf install --install_static_libs --install_path $GOPATH/src/github.com/steinwurf/kodo-rlnc-c`
I get the following waf error:
```
Load "waf-tools"                         : resolve_symlinks/waf-tools => /home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/resolved_dependencies/waf-tools-51dff5/4.27.0-64c29c 
Load "kodo-rlnc-c"                       : resolve_symlinks/kodo-rlnc-c => /home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/resolved_dependencies/kodo-rlnc-c-ec8def/4.0.0-c4176f 
Load "kodo-rlnc"                         : resolve_symlinks/kodo-rlnc => /home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/resolved_dependencies/kodo-rlnc-7d74ae/13.1.0-2918e7 
Load "kodo-core"                         : resolve_symlinks/kodo-core => /home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/resolved_dependencies/kodo-core-de4387/20.0.0-1d677d 
Load "boost"                             : resolve_symlinks/boost => /home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/resolved_dependencies/boost-abe3de/3.1.8-c2eaae 
Load "fifi"                              : resolve_symlinks/fifi => /home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/resolved_dependencies/fifi-8960fd/29.3.0-64fffa 
Load "allocate"                          : resolve_symlinks/allocate => /home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/resolved_dependencies/allocate-7c9f51/3.0.0-90a890 
Load "cpuid"                             : resolve_symlinks/cpuid => /home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/resolved_dependencies/cpuid-4d8071/5.0.2-146cbd 
Load "platform"                          : resolve_symlinks/platform => /home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/resolved_dependencies/platform-bccd32/3.1.0-7f3243 
Load "storage"                           : resolve_symlinks/storage => /home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/resolved_dependencies/storage-20a331/4.0.1-98878a 
Load "hex"                               : resolve_symlinks/hex => /home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/resolved_dependencies/hex-4d9037/4.1.1-a6e953 
Load "endian"                            : resolve_symlinks/endian => /home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/resolved_dependencies/endian-30a816/9.0.0-e1be57 
Waf: Entering directory `/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/build/linux'
Waf: Leaving directory `/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/build/linux'
Traceback (most recent call last):
  File "/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/.waf3-2.0.16-1ebfb5c5ab0101b67f0eea59e9db506c/waflib/Scripting.py", line 119, in waf_entry_point
    run_commands()
  File "/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/.waf3-2.0.16-1ebfb5c5ab0101b67f0eea59e9db506c/waflib/Scripting.py", line 182, in run_commands
    ctx=run_command(cmd_name)
  File "/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/.waf3-2.0.16-1ebfb5c5ab0101b67f0eea59e9db506c/waflib/Scripting.py", line 173, in run_command
    ctx.execute()
  File "/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/.waf3-2.0.16-1ebfb5c5ab0101b67f0eea59e9db506c/waflib/Scripting.py", line 370, in execute
    return execute_method(self)
  File "/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/.waf3-2.0.16-1ebfb5c5ab0101b67f0eea59e9db506c/waflib/Build.py", line 93, in execute
    self.execute_build()
  File "/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/.waf3-2.0.16-1ebfb5c5ab0101b67f0eea59e9db506c/waflib/Build.py", line 100, in execute_build
    self.compile()
  File "/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/.waf3-2.0.16-1ebfb5c5ab0101b67f0eea59e9db506c/waflib/Build.py", line 167, in compile
    self.producer.start()
  File "/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/.waf3-2.0.16-1ebfb5c5ab0101b67f0eea59e9db506c/waflib/Runner.py", line 275, in start
    self.refill_task_list()
  File "/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/.waf3-2.0.16-1ebfb5c5ab0101b67f0eea59e9db506c/waflib/Runner.py", line 152, in refill_task_list
    tasks=next(self.biter)
  File "/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/.waf3-2.0.16-1ebfb5c5ab0101b67f0eea59e9db506c/waflib/Build.py", line 414, in get_build_iterator
    self.post_group()
  File "/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/.waf3-2.0.16-1ebfb5c5ab0101b67f0eea59e9db506c/waflib/Build.py", line 397, in post_group
    tgpost(tg)
  File "/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/.waf3-2.0.16-1ebfb5c5ab0101b67f0eea59e9db506c/waflib/Build.py", line 359, in tgpost
    f()
  File "/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/.waf3-2.0.16-1ebfb5c5ab0101b67f0eea59e9db506c/waflib/TaskGen.py", line 123, in post
    v()
  File "/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/.waf3-2.0.16-1ebfb5c5ab0101b67f0eea59e9db506c/waflib/Build.py", line 451, in process_install_task
    self.add_install_task(**self.__dict__)
  File "/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/.waf3-2.0.16-1ebfb5c5ab0101b67f0eea59e9db506c/waflib/Build.py", line 473, in add_install_task
    tsk.init_files()
  File "/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/.waf3-2.0.16-1ebfb5c5ab0101b67f0eea59e9db506c/waflib/Build.py", line 499, in init_files
    inputs=self.generator.to_nodes(self.install_from)
  File "/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/.waf3-2.0.16-1ebfb5c5ab0101b67f0eea59e9db506c/waflib/TaskGen.py", line 237, in to_nodes
    tmp.extend(self.to_nodes(x))
  File "/home/juan/go/src/github.com/steinwurf/kodo-rlnc-go/.waf3-2.0.16-1ebfb5c5ab0101b67f0eea59e9db506c/waflib/TaskGen.py", line 231, in to_nodes
    for x in Utils.to_list(lst):
TypeError: 'NoneType' object is not iterable
```

I could update the go bindings if I manage to solve that issue.

Sorry for the inconveniences.

**Comment by jpihl** [comment]
The bindings now uses kodo-rlnc-c version 4 :) I've added a recode example which you might find useful. Enjoy!
